### PR TITLE
[IIGO] Update to our readme

### PR DESCRIPTION
**Pull request by Neelesh99**
# Summary
Noe's picture is too good to not be in our readme.md.

somas_2

### CODE REVIEW

**Comment by preetl** [comment]
pls be professional and provide pic in summary of change

**Comment by Neelesh99** [comment]
> pls be professional and provide pic in summary of change

I'm so sorry, pls no change request

**Comment by preetl** [comment]
> > pls be professional and provide pic in summary of change
> 
> I'm so sorry, pls no change request

bold of you to assume i know how to do that :D

**Comment by Neelesh99** [comment]
> > > pls be professional and provide pic in summary of change
> > 
> > 
> > I'm so sorry, pls no change request
> 
> bold of you to assume i know how to do that :D

I'm pretty sure you've done that to me XD

**Review by preetl — APPROVED** [review]
a classic 1, 2 to finish up ;) 
LOVE YOU ALL!

**Pull request merged**
