### PR TITLE
[TEAM 3] Agent v2.1 We patched some stuff, pls approve

### PR DESCRIPTION
**Pull request by Neelesh99**
# Summary

Many blood, sweat and tears have gone into this. Victor fought some fish, that was interesting. Agrim did 100 push-ups, and Preet removed go from her computer. We're done with this. ;)

### CODE REVIEW

**Review by preetl — APPROVED** [review]
yaaassss, let's beat up those fish!!!

**Comment by NGovani** [comment]
did a team 3 rep just approve a team 3 PR. This is very dissapointing

**Review by Spruudis — COMMENTED** [review]
I'm not sure how exactly this is  [TEAM4] but you do you

**Comment by Neelesh99** [comment]
> I'm not sure how exactly this is [TEAM4] but you do you

What you on about? XD

**Pull request merged**
