### PR TITLE
[INFRA/CORE] redefine server interface to have an EntryPoint

### PR DESCRIPTION
**Pull request by lhl2617**
# Summary

As title. EntryPoint returns a list of gameStates representing the beginning state of each day.
- Currently the game ends at day 2 as we `getEcho` and `kill` all clients at day 1

## Additional Information

- Altered some tests as necessary
- make other functions other than `EntryPoint` for SOMASServer private.
- added copy functions for `ClientInfo` and `GameState`... golang is inferior here :/

## Test Plan

- `go test ./...`
```
?       github.com/SOMAS2020/SOMAS2020  [no test files]
?       github.com/SOMAS2020/SOMAS2020/internal/clients/team1   [no test files]
?       github.com/SOMAS2020/SOMAS2020/internal/clients/team2   [no test files]
?       github.com/SOMAS2020/SOMAS2020/internal/clients/team3   [no test files]
?       github.com/SOMAS2020/SOMAS2020/internal/clients/team4   [no test files]
?       github.com/SOMAS2020/SOMAS2020/internal/clients/team5   [no test files]
?       github.com/SOMAS2020/SOMAS2020/internal/clients/team6   [no test files]
ok      github.com/SOMAS2020/SOMAS2020/internal/common  (cached)
ok      github.com/SOMAS2020/SOMAS2020/internal/common/rules    (cached)
ok      github.com/SOMAS2020/SOMAS2020/internal/server  (cached)
?       github.com/SOMAS2020/SOMAS2020/pkg/testutils    [no test files]
```

- `go run .`
```
2020/12/04 16:07:55 Team2
2020/12/04 16:07:55 [Team1]: Echo: 'HELLO WORLD!'
2020/12/04 16:07:55 [SERVER]: Received echo `HELLO WORLD!` from Team1
2020/12/04 16:07:55 [Team2]: Echo: 'HELLO WORLD!'
2020/12/04 16:07:55 [SERVER]: Received echo `HELLO WORLD!` from Team2
2020/12/04 16:07:55 [Team3]: Echo: 'HELLO WORLD!'
2020/12/04 16:07:55 [SERVER]: Received echo `HELLO WORLD!` from Team3
2020/12/04 16:07:55 [Team4]: Echo: 'HELLO WORLD!'
2020/12/04 16:07:55 [SERVER]: Received echo `HELLO WORLD!` from Team4
2020/12/04 16:07:55 [Team5]: Echo: 'HELLO WORLD!'
2020/12/04 16:07:55 [SERVER]: Received echo `HELLO WORLD!` from Team5
2020/12/04 16:07:55 [Team6]: Echo: 'HELLO WORLD!'
2020/12/04 16:07:55 [SERVER]: Received echo `HELLO WORLD!` from Team6
===== DAY 1 =====
common.GameState{Day:1, ClientInfos:map[common.ClientID]common.ClientInfo{0:common.ClientInfo{Client:(*team1.client)(0xc0000120c8), Resources:0x64, Alive:true}, 1:common.ClientInfo{Client:(*team2.client)(0xc000013870), Resources:0x64, Alive:true}, 2:common.ClientInfo{Client:(*team3.client)(0xc000013878), Resources:0x64, Alive:true}, 3:common.ClientInfo{Client:(*team4.client)(0xc000013880), Resources:0x64, Alive:true}, 4:common.ClientInfo{Client:(*team5.client)(0xc000013888), Resources:0x64, Alive:true}, 5:common.ClientInfo{Client:(*team6.client)(0xc000013890), Resources:0x64, Alive:true}}}
===== DAY 2 =====
common.GameState{Day:2, ClientInfos:map[common.ClientID]common.ClientInfo{0:common.ClientInfo{Client:(*team1.client)(0xc0000120c8), Resources:0x64, Alive:false}, 1:common.ClientInfo{Client:(*team2.client)(0xc000013870), Resources:0x64, Alive:false}, 2:common.ClientInfo{Client:(*team3.client)(0xc000013878), Resources:0x64, Alive:false}, 3:common.ClientInfo{Client:(*team4.client)(0xc000013880), Resources:0x64, Alive:false}, 4:common.ClientInfo{Client:(*team5.client)(0xc000013888), Resources:0x64, Alive:false}, 5:common.ClientInfo{Client:(*team6.client)(0xc000013890), Resources:0x64, Alive:false}}}
```

### CODE REVIEW

**Comment by QFSW** [comment]
# ⚠️Warning! This diff contains changes in protected folders

**Comment by lhl2617** [comment]
im preventing an import cycle problem with `common.ClientID` first

**Comment by lhl2617** [comment]
reopening later

**Comment by lhl2617** [comment]
# ⚠️  note to self: squash this boi

**Review by JamesTev — APPROVED** [review]
EntryPoint will be helpful - thanks @lhl2617. Was also unsure how to fix that import cycle without making a new package so glad that's fixed now. All looks good for now - hopefully stays that way when I integrate the disaster stuff 🌪️

**Pull request merged**
