### PR TITLE
fixed foraging plot colors so they're legible again (:

### PR DESCRIPTION
**Pull request by yp717**
# Summary

Please provide a summary of the change.

## Additional Information

Auxiliary information goes here.

## Test Plan

- Add information on how you tested your changes.

### CODE REVIEW

**Comment by lhl2617** [comment]
screenshots?

**Review by Darrekt — APPROVED** [review]
🌈

**Review by lhl2617 — APPROVED** [review]
lgtm but screenshots would be nice

image

**Comment by yp717** [comment]
image

Same as original the colours were changed so that they were all green before

**Pull request merged**
