### PR TITLE
Patch: fix disasters not reducing CP properly

### PR DESCRIPTION
**Pull request by JamesTev**
# Summary

Fix for #298 @NGovani 

## Test Plan

Test isn't the prettiest but seems to serve its purpose. Too tired to do anything fancier.

### CODE REVIEW

**Comment by QFSW** [comment]
# ⚠️Warning! This diff contains changes in protected folders

**Comment by NGovani** [comment]
I added a commit updating the clients resources when depleting their resources.
Initial problem was caused when we changed how resources were taken from the client.  It's causing pull issues. @JamesTev could you give it a quick look I dont have access to a go enviroment rn. Its only 1 line

**Comment by JamesTev** [comment]
> I added a commit updating the clients resources when depleting their resources.
> Initial problem was caused when we changed how resources were taken from the client. It's causing pull issues. @JamesTev could you give it a quick look I dont have access to a go enviroment rn. Its only 1 line

Done

**Review by NGovani — APPROVED** [review]
LGTM

**Pull request merged**
