### PR TITLE
[IIGO] Move TurnHistory into GameState from global

### PR DESCRIPTION
**Pull request by lhl2617**
# Summary

- `TurnHistory` should not have existed. This should've been in the `GameState`. Partially addresses #125 
- `output.json` now shows correct IIGOHistory instead of the SAME IIGOHistory  for EVERY turn. Each turn has its own individual IIGOHistory now.

## Additional Information

- Found error in IIGO running

## Test Plan

- As there are no test cases that exercise the code I changed, there is no feasible way of testing. It was broken before I fixed it, so I cannot confirm. Feel free to take over this PR and test it.

### CODE REVIEW

**Comment by QFSW** [comment]
# ⚠️Warning! This diff contains changes in protected folders

**Comment by Neelesh99** [comment]
Thanks for doing this @lhl2617, I found the FixMe, in essence, this was us not using error's as intended. We were using them as a generic datatype to pass data rather than their proper use. I've now refactored the return of runIIGO so that it provides both a boolean status and a message (which is logged if that particular run of IIGO was unsuccessful)

**Review by Neelesh99 — APPROVED** [review]
I'm happy with these changes, thanks @lhl2617 for doing them. Apologies again or our misuse of error (it was just so convenient ;) ). Feel free to merge.

**Comment by lhl2617** [comment]
@Neelesh99 I'll remove the fixmes then :) thanks!

**Review by NGovani — APPROVED** [review]
Yup all the changes make sense and look good

**Review by preetl — COMMENTED** [review]
posthumous approval! maybe a silly question but i'm just wondering if there will there will be a way of accessing previous turn's IIGOHistory? We will be extending the Judge functionality in our post-MVP tasks to have the option of checking historical events.

**Comment by lhl2617** [comment]
@preetl can you make an issue and assign to me pls

**Comment by lhl2617** [comment]
@preetl `IIGOHistory` is accumulated from start of the game. It is _NOT_ reset at the start of the next turn.

**Comment by preetl** [comment]
> @preetl `IIGOHistory` is accumulated from start of the game. It is _NOT_ reset at the start of the next turn.

@lhl2617 brilliant! that's perfect for our use case :)

**Pull request merged**
