### PR TITLE
Team1 foraging agent

### PR DESCRIPTION
**Pull request by mpardalos**
# Summary

Add the first iteration of the agent for team 1. It simply forages based on past foraging outcomes.

### CODE REVIEW

**Comment by QFSW** [comment]
# ⚠️Warning! This diff contains changes in protected folders

**Comment by mpardalos** [comment]
> # warningWarning! This diff contains changes in protected folders

@QFSW I think your warning is broken

**Comment by QFSW** [comment]
> > # warningWarning! This diff contains changes in protected folders
> 
> @QFSW I think your warning is broken

wow clapped

**Review by QFSW — APPROVED** [review]
LGTM other than lint issues

**Pull request closed without merging**
