### PR TITLE
[INFRA/CORE] Update docs

### PR DESCRIPTION
**Pull request by lhl2617**
As title

### CODE REVIEW

**Comment by QFSW** [comment]
# ⚠️Warning! This diff contains changes in protected folders

**Comment by lhl2617** [comment]
@Darrekt  can you follow the steps for the website for our fork just to make sure the instructions are correct? thx :D

**Review by QFSW — APPROVED** [review]
I would add a link to the website in the main README for convenience but other than that all looks good to me

**Comment by lhl2617** [comment]
@QFSW  added in the repo :) 
image

waiting for @Darrekt to check the website thign now

**Review by Darrekt — APPROVED** [review]

**Pull request merged**
