### PR TITLE
[VIS] Add 404 page

### PR DESCRIPTION
**Pull request by lhl2617**
# Summary

As title. Added also into `Switch` components as a fallback

- `http://localhost:3000/SOMAS2020#/visualisation/resources21`
  image

- `http://localhost:3000/SOMAS2020#/123`
  image

## Test Plan

Everything works, even `Go Home` and `Go Back`.

### CODE REVIEW

**Comment by QFSW** [comment]
# ⚠️Warning! This diff contains changes in protected folders

**Comment by yp717** [comment]
lgtm - can this be our 404 page too? not sure if we have one?

**Review by yp717 — APPROVED** [review]
lgtm

**Review by Darrekt — APPROVED** [review]
dancing bear

**Pull request merged**
