### PR TITLE
Main skeleton + CI

### PR DESCRIPTION
**Pull request by lhl2617**
Test plan:
```bash
$ go test ./...
?       github.com/SOMAS2020/SOMAS2020  [no test files]
?       github.com/SOMAS2020/SOMAS2020/internal/clients/team1   [no test files]
?       github.com/SOMAS2020/SOMAS2020/internal/clients/team2   [no test files]
?       github.com/SOMAS2020/SOMAS2020/internal/clients/team3   [no test files]
?       github.com/SOMAS2020/SOMAS2020/internal/clients/team4   [no test files]
?       github.com/SOMAS2020/SOMAS2020/internal/clients/team5   [no test files]
?       github.com/SOMAS2020/SOMAS2020/internal/clients/team6   [no test files]
?       github.com/SOMAS2020/SOMAS2020/internal/common  [no test files]
ok      github.com/SOMAS2020/SOMAS2020/internal/server  (cached)
```

```bash
$ go run .
2020/11/25 17:07:20 [1]: Echo: 'Hello World'
2020/11/25 17:07:20 [SERVER]: Received echo `Hello World` from client 1
2020/11/25 17:07:20 [2]: Echo: 'Hello World'
2020/11/25 17:07:20 [SERVER]: Received echo `Hello World` from client 2
2020/11/25 17:07:20 [3]: Echo: 'Hello World'
2020/11/25 17:07:20 [SERVER]: Received echo `Hello World` from client 3
2020/11/25 17:07:20 [4]: Echo: 'Hello World'
2020/11/25 17:07:20 [SERVER]: Received echo `Hello World` from client 4
2020/11/25 17:07:20 [5]: Echo: 'Hello World'
2020/11/25 17:07:20 [SERVER]: Received echo `Hello World` from client 5
2020/11/25 17:07:20 [6]: Echo: 'Hello World'
2020/11/25 17:07:20 [SERVER]: Received echo `Hello World` from client 6
```

CI initiated:
https://github.com/SOMAS2020/SOMAS2020/pull/2/checks?check_run_id=1454910250

image

image

### CODE REVIEW

**Comment by lhl2617** [comment]
setting up ci here too, brb.

**Comment by preetl** [comment]
lovely!

**Comment by lhl2617** [comment]
@preetl  whoops - can you reopen? i think you meant to review instead of closing :)

**Comment by lhl2617** [comment]
actually nevermind, reopening another :)

**Comment by preetl** [comment]
oh i'm so sorry :o

**Pull request closed without merging**
