### PR TITLE
[INFRA/CORE] Switched to new action that may work with fork PRs

### PR DESCRIPTION
**Pull request by QFSW**
# Summary

issue #16 
Switched to new action that may work with fork PRs

## Additional Information

Uses proxy hosted on my gcloud instance

### CODE REVIEW

**Comment by QFSW** [comment]
# ⚠️Warning! This diff contains changes in protected folders

**Comment by QFSW** [comment]
I guess this works but it looks like I'm the one making the comment as opposed to a bot or something, are we good with that?

**Comment by Eirikalb** [comment]
It looks fine, but might be better to have it in the initial PR comment? If thats hard to do, it looks good to me as is.

**Review by Eirikalb — APPROVED** [review]

**Review by lhl2617 — APPROVED** [review]
@Eirikalb has spoken

**Comment by QFSW** [comment]
> It looks fine, but might be better to have it in the initial PR comment? If thats hard to do, it looks good to me as is.

This action looks like it might do the trick, but then we go back into the whole issue of getting it working with a fork PR again
https://github.com/marketplace/actions/pull-request-updater-github-action

**Pull request merged**
