### PR TITLE
[INFRA/CORE] Add golang-ci-lint

### LINKED ISSUE #15: [INFRA/CORE] Add `golintci-lint-action` to repo.
Add https://github.com/golangci/golangci-lint-action into the main repo.

### PR DESCRIPTION
**Pull request by lhl2617**
# Summary

As title

## Additional Information

Resolves #15 

## Test Plan
On PR.

### CODE REVIEW

**Comment by QFSW** [comment]
# ⚠️Warning! This diff contains changes in protected folders

**Review by QFSW — APPROVED** [review]

**Comment by QFSW** [comment]
Seems to work to me

**Comment by QFSW** [comment]
Might want to make a new branch/PR so these test commits dont become part of the git history

**Comment by lhl2617** [comment]
image
neat!

**Comment by lhl2617** [comment]
@QFSW git rebase + git push --force :)

**Pull request merged**
